Add get_records() to API and df() to Registry
laminlabs/laminr pull request #54
Opened 2024-10-18 13:12 UTC by lazappi

Adds a `get_records()` method to the `InstanceAPI` class which performs the API call to retrieve record summary information and a `df()` method to the `Registry` class which makes the required API calls to get the requested number of records and formats the returned information as a `data.frame()`. This tries to be semi-smart to limit the number of API calls.

Checks:

- [ ] CI runs
- [ ] Update `CHANGELOG`

2024-10-18 13:16 UTC, lazappi commented on R/Registry.R
> +    #' @return A data.frame containing the available records
This might be nicer as a `tibble` but would need an extra dependency

2024-10-18 13:16 UTC, lazappi commented on R/Registry.R
> +          }
If there is a way to get the total number of records we can use a regular `purrr::map` instead

2024-10-23 19:02 UTC, rcannood requested changes
Nice!

Could you add a unit test for df()?

2024-10-24 06:05 UTC, lazappi commented on R/Registry.R
> +    #' @return A data.frame containing the available records
I checked but surprisingly only through suggested dependencies at the moment

2024-10-24 13:25 UTC, rcannood approved these changes
LGTM!

2024-10-25 06:26 UTC, merged